### ISSUE TITLE
setup directory is required?

### ISSUE THREAD

**Issue by danslo** [davidalger/capistrano-magento2#30]
Do you know why this is the case? When I do a deployment without checking this directory into version control, the deployment fails

**Comment by davidalger** [comment]
@danslo Can you post the error output you're seeing? We don't check any setup directory into the repo on our deployments, and they are running fine atm.

**Comment by danslo** [comment]
Sorry, I should've posted that earlier. I deleted the directory now and it's smooth sailing. I suppose it might just happen during initial deployments. Doesn't seem that big of a deal.

**Comment by danslo** [comment]
And just when I say that, I do another deployment and it breaks...

```
** Refer to log/capistrano.log for details. Here are the last 20 lines:


  INFO [f9b76d61] Running /usr/bin/env chmod +x ./bin/magento as mysite@staging.mysite.nl

 DEBUG [f9b76d61] Command: cd /home/mysite/domains/staging.mysite.nl/releases/20160922175323 && /usr/bin/env chmod +x ./bin/magento

  INFO [f9b76d61] Finished in 0.031 seconds with exit status 0 (successful).

 DEBUG [83802bcb] Running if test ! -d /home/mysite/domains/staging.mysite.nl/releases/20160922175323; then echo "Directory does not exist '/home/mysite/domains/staging.mysite.nl/releases/20160922175323'" 1>&2; false; fi as mysite@staging.mysite.nl

 DEBUG [83802bcb] Command: if test ! -d /home/mysite/domains/staging.mysite.nl/releases/20160922175323; then echo "Directory does not exist '/home/mysite/domains/staging.mysite.nl/releases/20160922175323'" 1>&2; false; fi

 DEBUG [83802bcb] Finished in 0.027 seconds with exit status 0 (successful).

  INFO [782e3763] Running touch /home/mysite/domains/staging.mysite.nl/releases/20160922175323/pub/static/deployed_version.txt as mysite@staging.mysite.nl

 DEBUG [782e3763] Command: touch /home/mysite/domains/staging.mysite.nl/releases/20160922175323/pub/static/deployed_version.txt

  INFO [782e3763] Finished in 0.029 seconds with exit status 0 (successful).

  INFO [83c2d158] Running /usr/bin/env php -f bin/magento -- setup:static-content:deploy en_US nl_NL -t mysite/default -t Magento/backend | stdbuf -o0 tr -d . as mysite@staging.mysite.nl

 DEBUG [83c2d158] Command: cd /home/mysite/domains/staging.mysite.nl/releases/20160922175323 && /usr/bin/env php -f bin/magento -- setup:static-content:deploy en_US nl_NL -t mysite/default -t Magento/backend | stdbuf -o0 tr -d .

 DEBUG [83c2d158]   PHP Warning:  Uncaught Exception: Warning: require(/home/mysite/domains/staging.mysite.nl/releases/20160922175323/setup/config/application.config.php): failed to open stream: No such file or directory in /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/Console/Cli.php on line 57 in /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/App/ErrorHandler.php:61

Stack trace:

#0 /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/Console/Cli.php(57): Magento\Framework\App\ErrorHandler->handler(2, 'require(/home/m...', '/home/mysite/do...', 57, Array)

#1 /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/Console/Cli.php(57): require()

#2 /home/mysite/domains/staging.mysite.nl/releases/20160922175323/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')

#3 {main}

  thrown in /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/App/ErrorHandler.php on line 61

 DEBUG [83c2d158]   PHP Fatal error:  Magento\Framework\Console\Cli::__construct(): Failed opening required '/home/mysite/domains/staging.mysite.nl/releases/20160922175323/setup/config/application.config.php' (include_path='/home/mysite/domains/staging.mysite.nl/releases/20160922175323/var/generation:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/lib/internal:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/zendframework1/library:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/phpunit/phpunit-mock-objects:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/phpunit/php-file-iterator:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/phpunit/phpunit:/home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/symfony/yaml:.:/usr/share/php') in /home/mysite/domains/staging.mysite.nl/releases/20160922175323/vendor/magento/framework/Console/Cli.php on line 57

  INFO [83c2d158] Finished in 0.321 seconds with exit status 0 (successful).
```

**Comment by danslo** [comment]
But then again, this looks like something that should be solved upstream. Not sure why `Magento\Framework\Console\Cli` does a require on those files.

**Comment by davidalger** [comment]
@danslo You might check the log/capistrano.log to see if the complete log tells of any other errors. I believe the file `setup/config/application.config.php` is deployed when the composer install runs (it is here in a test I did). I'm not sure why it wouldn't exist at the point of trying to generate static content unless something is failing the composer install.

**Comment by danslo** [comment]
That might be because I don't use Magento's specific metapackage (I think), to have composer.json as clean as possible:

`"magento/product-community-edition": "~2.1.1",`

**Comment by dooblem** [comment]
I had a similar problem.

During the composer install magento should copy a lot of files (setup, .htaccess, bin/magento...). In my case half of the files where copied: bin/magento was here, but no setup directory.

To see the error I had to run composer install with -vvv. It showed a permission problem in a linked directory (media in my case).

**Comment by hostep** [comment]
@dooblem, there was a very similar report on the magento2 repo a while ago: https://github.com/magento/magento2/issues/10292
They were unable to reproduce at the time, but if you have more info or an exact way to reproduce, it would be nice if you can list the exacts steps on that issue so we can re-open it for further investigation.

**Comment by dooblem** [comment]
Good advice. I thought at first it was a different problem. But the symlink problem may be a permission problem instead. I will do that.
